### ISSUE TITLE
Can't start mysql server after installing Nostrcheck server in vps

### ISSUE THREAD

**Issue by noubre** [quentintaranpino/nostrcheck-api-ts#19]
After installing notrcheck and then installing mysql server. When I try and start up mysql I get this error:

"Job for mysql.service failed because the control process exited with error code."

I am running on an Ubuntu machine. When I create a fresh vps without nostrcheck installed, I can start mysql without an issue. I can't figure out what I did wrong. Should I have installed mysql first?

**Comment by quentintaranpino** [comment]
Hi, could you please tell me which version you are installing? The main branch or the 0.5.0 branch?

**Comment by noubre** [comment]
I ended up figuring it out, sorry for not responding sooner. Thanks!
