### ISSUE TITLE
Video aspect ratio changes

### ISSUE THREAD

**Issue by Lokuyow** [quentintaranpino/nostrcheck-api-ts#22]
**Describe the bug**
The uploaded video was compressed vertically and the aspect ratio became abnormal.

**Original video**
- 12.79MB
- 1080x2316
- 0:24
- H.264
- AAC
- 55fps
- https://drive.google.com/file/d/1RM3j6pyfycLLcIpZZJXMZD6sVIFw-JVM/view?usp=drive_link

**Uploaded video**
https://nostrcheck.me/media/ec42c765418b3db9c85abff3a88f4a3bbe57535eebbdc54522041fa5328c0600/9442246c7960886d40e1dca5725ee2576bebc258173ceb6c9d4930766282ebca.mp4

**Smartphone**
 - Device: Galaxy Note20 Ultra 5G
 - OS: Android 13
 - Browser Firefox
 - Version 124.2.0

**Comment by quentintaranpino** [comment]
Sorry, I've been away for a few weeks. I'll check it out right away.

**Comment by quentintaranpino** [comment]
I have already found the problem. In this particular video the audio stream is before the video stream and my server was not able to recognize the size (returning 640x480 as standard).

I have already detected the problem, I am working on it.

**Comment by quentintaranpino** [comment]
It is already solved. The patch will be available in version 0.6.0 that I will release in the next weeks. 

Thank you very much for notifying me the bug 🙂

**Comment by Lokuyow** [comment]
Thank you very much!
