### ISSUE TITLE
Deleted error is shown immediately after uploading a image

### ISSUE THREAD

**Issue by SnowCait** [quentintaranpino/nostrcheck-api-ts#23]
**Describe the bug**

"The requested file has been deleted" image is sometimes (10%+?) shown immediately after uploading a image.
After several minutes (not seconds), same URL shows the uploaded image correctly.

**To Reproduce**

1. Upload image through API with NIP-96 flow
2. Access the URL

**Expected behavior**

No error or show a proccessing image instead of a deleted image. (Sad if deleted😢)

**Screenshots**

<img src="https://github.com/quentintaranpino/nostrcheck-api-ts/assets/1297512/9ee249a9-a2e9-471e-80c9-153ccb6e8de4" width="30%">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 124.0.6367.119

**Smartphone (please complete the following information):**

**Additional context**

The time until correct image is shown seems to be consumed by converting process or something.

**Comment by quentintaranpino** [comment]
First of all, I've been offline for a few weeks, sorry for the delay.

I'm going to check this out right now.

**Comment by quentintaranpino** [comment]
I have detected the problem. Somehow the redis cache does not allow to show the original file until the 300 seconds (5 minutes) of cache that I have specified in the server have passed. 

To mitigate the problem I have lowered it to 10 seconds. Now I will continue working to solve it definitively. 

Once again, sorry for any inconvenience caused.

**Comment by quentintaranpino** [comment]
The problem was because Nostter performs the GET of the uploaded file very fast, then my server does not mark the file as "active" until it has been processed, the first GET "marks" the file as not active for 5 minutes until the cache is cleared and then everything works. 

It was clearly a design problem on my part with the flow of file uploads. 

It should be fixed by now, can you try it on your end?

**Comment by SnowCait** [comment]
Thank you! I'll keep an eye on it for a while.

**Comment by SnowCait** [comment]
I've never seen deleted error these days🎉
Thanks again!
