### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by cezar1** [quentintaranpino/nostrcheck-api-ts#25]
https://github.com/quentintaranpino/nostrcheck-api-ts/blob/12a46fa0da9ea56c69b11bfe4a7c86ab077762a2/src/lib/domains.ts#L1

You're doing import database.js but the file in the project root is database.ts . Is this a typescript thing where the typescript will at some point be converted to javascript ?

Sorry if the question level is very low. I find your project very interesting and trying to learn it step by step.

**Comment by quentintaranpino** [comment]
Hello cezar1

According to the ECMAScript specification, module files need to have the .js extension. So, TypeScript uses .js in import paths to stay compatible and make sure everything works smoothly.
