### ISSUE TITLE
Potential issue with NIP-05 route

### ISSUE THREAD

**Issue by TheSameCat2** [quentintaranpino/nostrcheck-api-ts#6]
**Describe the bug**
Users added to the registered table are not able to validate their NIP-05 address at the server domain.

**To Reproduce**
1. Add a user to the registered table
2. Attempt to visit <domain>/.well-known/nostr.json?name=<local-part>
3. Receive an error about not being able to load /api/v2/nostraddress

**Expected behavior**
A JSON object containing the user's name and npub should be returned:
i.e. 
```
https://sove.rent/.well-known/nostr.json?name=thesamecat

output:
{"names":{"thesamecat":"72f9755501e1a4464f7277d86120f67e7f7ec3a84ef6813cc7606bf5e0870ff3"}}
```

**Desktop (please complete the following information):**
 - OS: macOS Sonoma
 - Browser: Thorium, Gossip, Damus
 - Version: current (all)

**Smartphone (please complete the following information):**
 - Device: iPhone 15 Pro Max, iMac
 - OS: iOS 17.1, macOS Sonoma
 - Browser: Damus
 - Version: TestFlight

**Additional context**
I was able to temporarily fix this by adding:
```
        if (version == "v2"){
                app.get("/api/v2/nostraddress", Checknostraddress);
        }
```
to src/routes/nostraddress.route.ts

**Comment by quentintaranpino** [comment]
Thank you very much for opening the issue @TheSameCat2, solved here:

https://github.com/quentintaranpino/nostrcheck-api-ts/commit/e4cfa6608962857ded5c6c980da055ae66eb4349

**Comment by TheSameCat2** [comment]
Will update later today. Thanks @quentintaranpino
